const ProductosData=[
    {id:1,
    nombre:"Matambre de cerdo",
    tipo:"cerdo",
    Marca:"x",
    precio:2500,
    stock:100,
    cantidad:1,
    img:'galeria/matambre_de_cerdo.JPG'},

    {id:2,
    nombre:"Paleta de cerdo",
    tipo:"cerdo",
    Marca:"x",
    precio:2000,
    stock:100,
    cantidad:1,
    img:'../galeria/paleta_de_cerdo.jpg'},

    {id:3,
    nombre:"Pechito de cerdo",
    tipo:"cerdo",
    Marca:"x",
    precio:2700,
    stock:100,
    cantidad:1,
    img:'galeria/pechito_de_cerdo.jpg'},


    {id:4,
    nombre:"Asado americano",
    tipo:"cerdo", 
    Marca:"x", 
    precio:2100, 
    stock:100, 
    cantidad:1, 
    img:'galeria/asado_americano.jpg'},

    {id:5,
    nombre:"Ribs de cerdo", 
    tipo:"cerdo", 
    Marca:"x", 
    precio:2900, 
    stock:100, 
    cantidad:1, 
    img:'galeria/ribs_de_cerdo.JPG'},

    {id:7,
    nombre:"Bondiola", 
    tipo:"cerdo",
    Marca:"x", 
    precio:2500, 
    stock:100, 
    cantidad:1, 
    img:'galeria/bondiola_cerdo.jpg'},

    {id:8,
    nombre:"Solomillo", 
    tipo:"cerdo", 
    Marca:"x", 
    precio:2800, 
    stock:100, 
    cantidad:1, 
    img:'galeria/solomillo.jpg'},

    {id:9,
    nombre:"Chorizos puro cerdo", 
    tipo:"Achuras", 
    Marca:"x", 
    precio:1700, 
    stock:100, 
    cantidad:1, 
    img:'galeria/chorizo_de_cerdo.jpg'},


    {id:10, 
    nombre:"Churrasquito", 
    tipo:"cerdo", 
    Marca:"x", 
    precio:2300, 
    stock:100, 
    cantidad:1, 
    img:'galeria/churrasquito_de_cerdo.jpg'}
    ];

export default ProductosData;